/**
 * CreatePptxTool
 *
 * Creates PowerPoint presentations from HTML slides.
 * Each slide is HTML (1280×720px canvas) rendered via HtmlSlideParser → PptxGenJS.
 *
 * Corporate designs: use ingest_template first to generate a CSS theme,
 * then reference it via theme_name. The theme CSS is applied to all slides.
 *
 * Legacy fields (title, bullets, etc.) are supported for simple cases.
 */

import { BaseTool } from '../BaseTool';
import type { ToolDefinition, ToolExecutionContext } from '../types';
import { writeBinaryToVault } from './writeBinaryToVault';
import type ObsidianAgentPlugin from '../../../main';
import { CreatePptxService, type SlideInput } from './pptx/CreatePptxService';

export class CreatePptxTool extends BaseTool<'create_pptx'> {
    readonly name = 'create_pptx' as const;
    readonly isWriteOperation = true;
    private service: CreatePptxService;

    constructor(plugin: ObsidianAgentPlugin) {
        super(plugin);
        this.service = new CreatePptxService(plugin);
    }

    getDefinition(): ToolDefinition {
        return {
            name: 'create_pptx',
            description:
                'Create a PowerPoint presentation (.pptx) from HTML slides. ' +
                'Each slide is annotated HTML rendered on a 1280×720px canvas. ' +
                'For corporate designs: use theme_name to apply a CSS theme generated by ingest_template. ' +
                'Supports charts, tables, and speaker notes per slide. ' +
                'Never use write_file or evaluate_expression for .pptx files.',
            input_schema: {
                type: 'object',
                properties: {
                    output_path: {
                        type: 'string',
                        description: 'Vault path for the output file (must end with .pptx)',
                    },
                    theme_name: {
                        type: 'string',
                        description:
                            'Name of an ingested corporate theme (e.g. "acme"). ' +
                            'The theme CSS is automatically applied to all slides. ' +
                            'Use the name returned by ingest_template.',
                    },
                    slides: {
                        type: 'array',
                        description: 'Array of slides (max 60). Each slide is HTML or legacy fields.',
                        items: {
                            type: 'object',
                            properties: {
                                html: {
                                    type: 'string',
                                    description:
                                        'HTML for this slide. Canvas: 1280×720px. ' +
                                        'Use <div data-object="true" data-object-type="shape|textbox|image|chart|table" ' +
                                        'style="position:absolute; left:Xpx; top:Ypx; width:Wpx; height:Hpx;"> ' +
                                        'for each element. CSS classes from the theme are available.',
                                },
                                charts: {
                                    type: 'array',
                                    description: 'Chart data. Reference in HTML via data-chart-index="0".',
                                    items: {
                                        type: 'object',
                                        properties: {
                                            type: { type: 'string', enum: ['bar', 'pie', 'line'] },
                                            title: { type: 'string' },
                                            categories: { type: 'array', items: { type: 'string' } },
                                            series: {
                                                type: 'array',
                                                items: {
                                                    type: 'object',
                                                    properties: {
                                                        name: { type: 'string' },
                                                        values: { type: 'array', items: { type: 'number' } },
                                                        color: { type: 'string' },
                                                    },
                                                    required: ['name', 'values'],
                                                },
                                            },
                                        },
                                        required: ['type', 'categories', 'series'],
                                    },
                                },
                                tables: {
                                    type: 'array',
                                    description: 'Table data. Reference in HTML via data-table-index="0".',
                                    items: {
                                        type: 'object',
                                        properties: {
                                            headers: { type: 'array', items: { type: 'string' } },
                                            rows: { type: 'array', items: { type: 'array', items: {} } },
                                            style: {
                                                type: 'object',
                                                properties: {
                                                    headerColor: { type: 'string' },
                                                    headerTextColor: { type: 'string' },
                                                    zebraColor: { type: 'string' },
                                                },
                                            },
                                        },
                                    },
                                },
                                notes: {
                                    type: 'string',
                                    description: 'Speaker notes for this slide.',
                                },
                                // Legacy fields for simple slides
                                title: { type: 'string', description: 'Slide title (simple mode)' },
                                subtitle: { type: 'string', description: 'Subtitle (simple mode)' },
                                body: { type: 'string', description: 'Body text (simple mode)' },
                                bullets: { type: 'array', items: { type: 'string' }, description: 'Bullet points (simple mode)' },
                                layout: { type: 'string', description: 'Layout hint for simple mode' },
                            },
                        },
                    },
                    template: {
                        type: 'string',
                        description: 'Built-in theme: "executive" (dark), "modern" (blue), "minimal" (clean). Default: "executive".',
                    },
                },
                required: ['output_path'],
            },
        };
    }

    async execute(input: Record<string, unknown>, context: ToolExecutionContext): Promise<void> {
        const { callbacks } = context;
        const outputPath = ((input.output_path as string) ?? '').trim();

        if (!outputPath) {
            callbacks.pushToolResult(this.formatError(new Error('output_path is required')));
            return;
        }
        if (!outputPath.endsWith('.pptx')) {
            callbacks.pushToolResult(this.formatError(new Error('output_path must end with .pptx')));
            return;
        }

        let rawSlides: SlideInput[] = [];
        if (Array.isArray(input.slides)) {
            rawSlides = input.slides as SlideInput[];
        } else if (typeof input.slides === 'string') {
            try {
                const parsed = JSON.parse(input.slides);
                if (!Array.isArray(parsed)) throw new Error('slides must be a JSON array');
                rawSlides = parsed as SlideInput[];
            } catch (e) {
                callbacks.pushToolResult(this.formatError(e));
                return;
            }
        }

        const slides = rawSlides.slice(0, 60);
        const themeName = ((input.theme_name as string) ?? '').trim() || undefined;
        const templateRef = ((input.template as string) ?? 'executive').trim();

        if (slides.length === 0) {
            callbacks.pushToolResult(
                `Canvas: 1280×720px (16:9). Write HTML slides with data-object-type attributes.\n` +
                `Element types: shape, textbox, image, chart, table.\n` +
                `${themeName ? `Theme "${themeName}" CSS classes are available.\n` : ''}` +
                `Now call create_pptx again with your slides.`,
            );
            return;
        }

        try {
            const buildResult = await this.service.buildPresentation({
                slides,
                themeName,
                templateRef,
            });

            const writeResult = await writeBinaryToVault(this.app.vault, outputPath, buildResult.buffer, '.pptx');
            const action = writeResult.created ? 'Created' : 'Updated';
            const sizeKB = Math.round(writeResult.size / 1024);

            const warningsText = buildResult.warnings.length > 0
                ? '\n\n**Notes:**\n' + buildResult.warnings.slice(0, 5).map(w => `- ${w}`).join('\n')
                : '';

            callbacks.pushToolResult(
                `${action} **${outputPath}**\n` +
                `- ${slides.length} slide${slides.length !== 1 ? 's' : ''}\n` +
                `- Theme: ${buildResult.themeName}\n` +
                `- Size: ${sizeKB} KB` +
                warningsText,
            );
            callbacks.log(`${action} PPTX: ${outputPath} (${slides.length} slides, ${sizeKB} KB)`);
        } catch (error) {
            callbacks.pushToolResult(this.formatError(error));
            await callbacks.handleError('create_pptx', error);
        }
    }
}
