/**
 * GetCompositionDetailsTool — Two-Tier Retrieval (FEATURE-1115)
 *
 * Reads composition details from a template's compositions.json file.
 * Returns only the requested compositions (not all), keeping context window usage minimal.
 *
 * The compositions.json is generated by AnalyzePptxTemplateTool during template analysis
 * and enriched by the agent during visual inspection.
 */

import { BaseTool } from '../BaseTool';
import type { ToolDefinition, ToolExecutionContext } from '../types';
import type ObsidianAgentPlugin from '../../../main';
import { normalizeTemplateSlug } from './compositionsFile';
import { CompositionsRepository } from './pptx/CompositionsRepository';
import type { CompositionEntry, CompositionsFile, RepeatableGroupEntry, ShapeDetailEntry } from './pptx/compositionsSchema';

export class GetCompositionDetailsTool extends BaseTool<'get_composition_details'> {
    readonly name = 'get_composition_details' as const;
    readonly isWriteOperation = false;
    private repository: CompositionsRepository;

    constructor(plugin: ObsidianAgentPlugin) {
        super(plugin);
        this.repository = new CompositionsRepository(plugin.app.vault.adapter);
    }

    getDefinition(): ToolDefinition {
        return {
            name: 'get_composition_details',
            description:
                'Get detailed shape mappings and constraints for specific compositions from a template. ' +
                'Use this AFTER reading the template skill (which lists available compositions) ' +
                'to get the exact shape names, text capacity limits, and usage rules needed for create_pptx. ' +
                'Only request the compositions you actually need (typically 1-5 per presentation).',
            input_schema: {
                type: 'object',
                properties: {
                    template: {
                        type: 'string',
                        description:
                            'Template name (e.g., "acme-corporate"). ' +
                            'Must match the template field in the compositions.json file.',
                    },
                    compositions: {
                        type: 'array',
                        description:
                            'List of composition IDs to retrieve (e.g., ["chevron-kette", "kpi-dashboard"]). ' +
                            'IDs are listed in the template skill under "Compositions".',
                        items: { type: 'string' },
                    },
                },
                required: ['template', 'compositions'],
            },
        };
    }

    async execute(input: Record<string, unknown>, context: ToolExecutionContext): Promise<void> {
        const { callbacks } = context;
        const rawTemplate = (input.template as string ?? '').trim();
        const compositionIds = input.compositions as string[] ?? [];

        if (!rawTemplate) {
            callbacks.pushToolResult(this.formatError(new Error('Missing required parameter: template')));
            return;
        }

        if (compositionIds.length === 0) {
            callbacks.pushToolResult(this.formatError(new Error('Missing required parameter: compositions (array of IDs)')));
            return;
        }

        // Normalize template name (same logic as AnalyzePptxTemplateTool slug derivation)
        const template = normalizeTemplateSlug(rawTemplate);

        // Find compositions.json via adapter (filesystem-level, cache-independent).
        // vault.getFileByPath() uses the metadata cache which may not know about
        // files written via vault.adapter.write() by AnalyzePptxTemplateTool.
        const filePath = this.repository.getPath(template);
        let loaded: { path: string; data: CompositionsFile } | undefined;
        try {
            loaded = await this.repository.read(template);
        } catch {
            callbacks.pushToolResult(this.formatError(new Error(
                `Invalid compositions.json: ${filePath} could not be parsed.`,
            )));
            return;
        }

        if (!loaded) {
            // List available composition files for a helpful error message
            const availableTemplates = await this.repository.listTemplates();

            if (availableTemplates.length > 0) {
                callbacks.pushToolResult(this.formatError(new Error(
                    `Compositions file not found: ${filePath}. ` +
                    `Available templates: ${availableTemplates.join(', ')}. ` +
                    `Use one of these as the template parameter.`,
                )));
            } else {
                callbacks.pushToolResult(this.formatError(new Error(
                    `Compositions file not found: ${filePath}. ` +
                    `No template compositions found in vault. ` +
                    `Run analyze_pptx_template first to generate them.`,
                )));
            }
            return;
        }

        try {
            const data = loaded.data;

            if (!data.compositions) {
                callbacks.pushToolResult(this.formatError(new Error(
                    'Invalid compositions.json: missing "compositions" field.',
                )));
                return;
            }

            // Filter to requested compositions
            const results: string[] = [];
            const notFound: string[] = [];

            for (const id of compositionIds) {
                const comp = data.compositions[id];
                if (!comp) {
                    notFound.push(id);
                    continue;
                }

                results.push(this.formatComposition(id, comp, data.schema_version ?? 1));
            }

            // Build response
            let output = `## Composition Details (${template})\n\n`;

            // Show BrandDNA for HTML mode reference
            if (data.brand_dna) {
                output += `### Brand-DNA\n`;
                output += `Fonts: ${data.brand_dna.fonts.major} (headings) / ${data.brand_dna.fonts.minor} (body)\n`;
                output += `Canvas: ${data.brand_dna.slide_size_px.w}x${data.brand_dna.slide_size_px.h}px\n`;
                output += `Colors: ${Object.entries(data.brand_dna.colors).map(([k, v]) => `${k}=#${v}`).join(', ')}\n\n`;
            }

            if (results.length > 0) {
                output += results.join('\n\n---\n\n');
            }

            if (notFound.length > 0) {
                output += `\n\nCompositions not found: ${notFound.join(', ')}. ` +
                    `Available: ${Object.keys(data.compositions).join(', ')}`;
            }

            callbacks.pushToolResult(output);
        } catch (error) {
            callbacks.pushToolResult(this.formatError(error));
        }
    }

    private formatComposition(id: string, comp: CompositionEntry, schemaVersion: number): string {
        const lines: string[] = [];
        const isV2 = schemaVersion >= 2;
        const isV4 = schemaVersion >= 4;

        lines.push(`### ${comp.name} (ID: ${id})`);
        lines.push(`**Slides:** ${comp.slides.join(', ')}`);
        if (isV4 && comp.recommended_pipeline) lines.push(`**Pipeline:** ${comp.recommended_pipeline}`);
        if (isV4 && comp.recommended_pipeline_reason) lines.push(`**Pipeline Reason:** ${comp.recommended_pipeline_reason}`);

        if (comp.narrative_phase && comp.narrative_phase !== 'any') lines.push(`**Narrative Phase:** ${comp.narrative_phase}`);
        if (comp.bedeutung) lines.push(`**Bedeutung:** ${comp.bedeutung}`);
        if (comp.einsetzen_wenn) lines.push(`**Einsetzen wenn:** ${comp.einsetzen_wenn}`);
        if (comp.nicht_einsetzen_wenn) lines.push(`**Nicht einsetzen wenn:** ${comp.nicht_einsetzen_wenn}`);
        if (comp.visual_structure) lines.push(`**Visual Structure:** ${comp.visual_structure}`);
        if (comp.has_fixed_visuals) lines.push(`**Fixed Visuals:** ${comp.decorative_element_count ?? 0} fixed decorative elements (icons/images that cannot be replaced)`);
        if (comp.has_static_chart || comp.has_static_table || comp.has_static_picture) {
            const parts: string[] = [];
            if (comp.has_static_chart) parts.push('embedded charts');
            if (comp.has_static_table) parts.push('embedded tables');
            if (comp.has_static_picture) parts.push('fixed pictures/icons');
            lines.push(`**Static Objects:** ${parts.join(', ')}`);
        }

        // Scaffolding info (v4)
        if (isV4 && comp.content_area) {
            const ca = comp.content_area;
            lines.push(`\n**Content Area:** x=${ca.x}, y=${ca.y}, w=${ca.w}, h=${ca.h} (px, 1280x720 canvas)`);
        }
        if (isV4 && comp.style_guide) {
            const sg = comp.style_guide;
            const parts: string[] = [];
            if (sg.title) parts.push(`Title: ${sg.title.font_size_pt}pt ${sg.title.color} ${sg.title.font_weight}`);
            if (sg.body) parts.push(`Body: ${sg.body.font_size_pt}pt ${sg.body.color}`);
            if (sg.accent_color) parts.push(`Accent: ${sg.accent_color}`);
            if (parts.length > 0) lines.push(`**Style Guide:** ${parts.join(' | ')}`);
        }
        if (isV4 && comp.layout_hint) lines.push(`**Layout Hint:** ${comp.layout_hint}`);
        if (isV4 && comp.scaffold_elements) lines.push(`**Scaffold Elements:** ${comp.scaffold_elements.length} (auto-injected via composition_id)`);
        if (isV4 && comp.supports_html_overlay) lines.push('**Hybrid HTML Overlay:** Supported via `html` + `composition_id`');
        if (isV4 && comp.html_skeleton) {
            lines.push('\n**HTML Skeleton (starting point):**');
            lines.push('```html');
            lines.push(comp.html_skeleton);
            lines.push('```');
        }

        // HTML mode hint for v4 compositions with html pipeline
        if (isV4 && comp.recommended_pipeline === 'html') {
            lines.push('\n**Recommended: Use planner-driven hybrid mode or explicit HTML:**');
            lines.push('```yaml');
            lines.push(`composition_id: "${id}"`);
            lines.push('content:');
            lines.push('  "title": "YOUR TEXT HERE"');
            lines.push('  "content_1": "YOUR TEXT HERE"');
            lines.push('```');
            lines.push('> Preferred when you want the planner to turn the composition into a branded hybrid slide automatically using html_skeleton and scaffold metadata.');
            lines.push('');
            lines.push('```yaml');
            lines.push(`html: "<div ...>your content within content_area bounds</div>"`);
            lines.push(`composition_id: "${id}"  # scaffold auto-injected`);
            lines.push('```');
            lines.push('> Scaffold (header, footer, logo, deko) injected automatically. Design HTML within content_area bounds using style_guide colors/fonts. Treat the template slide as a branded reference, not as a rigid layout you must copy.');
        } else if (isV4 && comp.supports_html_overlay) {
            lines.push('\n**Optional hybrid mode:**');
            lines.push('```yaml');
            lines.push(`composition_id: "${id}"`);
            lines.push('content:');
            lines.push('  "title": "YOUR TEXT HERE"');
            lines.push('  "content_1": "YOUR TEXT HERE"');
            lines.push('```');
            lines.push('> The planner can use this to choose clone or hybrid HTML depending on deck_mode, fixed visuals, image placeholders, and text density.');
            lines.push('');
            lines.push('```yaml');
            lines.push(`html: "<div ...>your content within content_area bounds</div>"`);
            lines.push(`composition_id: "${id}"  # scaffold auto-injected`);
            lines.push('```');
            lines.push('> Use this when you want more layout freedom than clone mode offers, but still want the corporate scaffold from the template. The template is a branded reference implementation, not a strict visual ceiling.');
        }

        // Shape mappings: compact for HTML compositions, full for clone compositions
        if (isV4 && comp.recommended_pipeline === 'html') {
            // Compact clone-mode reference for HTML compositions
            const firstSlide = Object.entries(comp.shapes)[0];
            if (firstSlide) {
                const [slideNum, shapes] = firstSlide;
                const shapeNames = Object.keys(shapes);
                const warnings = comp.slide_warnings?.[slideNum];
                if (warnings && warnings.length > 0) {
                    lines.push(`\n**Representative slide warning (${slideNum}):** ${warnings.join('; ')}`);
                }
                lines.push(`\n**Clone mode reference** (prefer HTML mode above):`);
                lines.push(`Slide ${slideNum}: ${shapeNames.join(', ')}`);
            }
        } else {
            // Full shape mappings (clone mode or non-v4)
            const keyLabel = isV2 ? 'semantic aliases' : 'shape names';
            for (const [slideNum, shapes] of Object.entries(comp.shapes)) {
                lines.push(`\n**Slide ${slideNum} -- Use these exact ${keyLabel} as content keys in create_pptx:**`);
                const warnings = comp.slide_warnings?.[slideNum];
                if (warnings && warnings.length > 0) {
                    lines.push(`> Slide warning: ${warnings.join('; ')}`);
                }
                lines.push('```yaml');
                lines.push(`template_slide: ${slideNum}`);
                lines.push('content:');
                for (const [shapeName, detail] of Object.entries(shapes)) {
                    const constraints: string[] = [];
                    if (detail.shape_type === 'image') constraints.push('[IMAGE]');
                    if (detail.zweck) constraints.push(detail.zweck);
                    if (detail.fill_color) constraints.push(`fill: ${detail.fill_color}`);
                    if (detail.max_chars) constraints.push(`max ${detail.max_chars} chars`);
                    if (detail.font_size_pt) constraints.push(`${detail.font_size_pt}pt`);
                    if (detail.width_cm) constraints.push(`${detail.width_cm}cm wide`);
                    const constraintStr = constraints.length > 0 ? `  # ${constraints.join(', ')}` : '';
                    const placeholder = detail.shape_type === 'image' ? 'IMAGE PLACEHOLDER -- ask user or choose text-only composition' : 'YOUR TEXT HERE';
                    lines.push(`  "${shapeName}": "${placeholder}"${constraintStr}`);
                    if (detail.notes) lines.push(`    # ${detail.notes}`);
                }
                lines.push('```');
                if (isV2) {
                    lines.push('> Keys above are semantic aliases mapped to unique shape IDs. Use them EXACTLY as content keys.');
                } else {
                    lines.push('> Shape names above are OOXML name attributes. Use them EXACTLY as content keys.');
                }

                // Show repeatable groups for this slide
                const slideGroups = comp.repeatable_groups?.[slideNum];
                if (slideGroups && slideGroups.length > 0) {
                    lines.push('');
                    lines.push(`**Adaptable:** This slide has ${slideGroups.length} repeatable group(s). Shape count can be adjusted:`);
                    for (const rg of slideGroups) {
                        const shapeCount = rg.shapeNames.length;
                        const minCount = 2;
                        const maxCount = shapeCount + 3;
                        lines.push(`- **${rg.groupId}** (${rg.axis}): ${shapeCount}x shapes [${rg.shapeNames.slice(0, 3).join(', ')}${shapeCount > 3 ? '...' : ''}]. Adaptable to ${minCount}-${maxCount} shapes.`);
                        if (rg.columns.some(c => c.associatedShapes.length > 0)) {
                            const assocCount = rg.columns[0].associatedShapes.length;
                            lines.push(`  - Each shape has ${assocCount} associated element(s) that move together (e.g. description boxes below).`);
                        }
                        lines.push(`  - To use FEWER: provide the primary item keys you need; surplus columns and their associated shapes are removed automatically.`);
                        lines.push(`  - To use MORE: provide additional primary/associated keys with incrementing numbers.`);
                    }
                }
            }
        }

        return lines.join('\n');
    }
}
