/**
 * GetCompositionDetailsTool — Two-Tier Retrieval (FEATURE-1115)
 *
 * Reads composition details from a template's compositions.json file.
 * Returns only the requested compositions (not all), keeping context window usage minimal.
 *
 * The compositions.json is generated by AnalyzePptxTemplateTool during template analysis
 * and enriched by the agent during visual inspection.
 */

import { BaseTool } from '../BaseTool';
import type { ToolDefinition, ToolExecutionContext } from '../types';
import type ObsidianAgentPlugin from '../../../main';

/** Shape detail within a composition */
interface ShapeDetail {
    zweck: string;
    shape_id?: string;
    shape_type?: 'image' | 'text';
    fill_color?: string;
    max_chars?: number;
    min_chars?: number;
    font_size_pt?: number;
    width_cm?: number;
    notes?: string;
}

/** Composition entry in compositions.json */
interface CompositionEntry {
    name: string;
    classification?: string;
    narrative_phase?: string;
    slides: number[];
    bedeutung?: string;
    einsetzen_wenn?: string;
    nicht_einsetzen_wenn?: string;
    visual_structure?: string;
    decorative_element_count?: number;
    has_fixed_visuals?: boolean;
    /** Recommended pipeline: 'clone' for structural slides, 'html' for content (v4) */
    recommended_pipeline?: 'clone' | 'html';
    /** Per-composition scaffold elements count (v4) */
    scaffold_elements?: Array<{ id: string; type: string }>;
    /** Content area bounding box in px (v4) */
    content_area?: { x: number; y: number; w: number; h: number };
    /** Style guide for content rendering (v4) */
    style_guide?: {
        title?: { font_size_pt: number; color: string; font_weight: string };
        body?: { font_size_pt: number; color: string };
        accent_color?: string;
    };
    /** Layout hint for content arrangement (v4) */
    layout_hint?: string;
    /** HTML skeleton with placeholders (v4) */
    html_skeleton?: string;
    repeatable_groups?: Record<string, RepeatableGroupInfo[]>;
    shapes: Record<string, Record<string, ShapeDetail>>;
}

/** Repeatable group info from compositions.json */
interface RepeatableGroupInfo {
    groupId: string;
    axis: 'horizontal' | 'vertical';
    shapeNames: string[];
    shapeIds?: string[];
    boundingBox: { left: number; top: number; width: number; height: number };
    gap: number;
    shapeSize: { cx: number; cy: number };
    columns: Array<{
        index: number;
        primaryShape: string;
        primaryShapeId?: string;
        associatedShapes: Array<{ shapeName: string; shapeId?: string; offsetY: number; offsetX: number }>;
    }>;
}

/** Root structure of compositions.json */
interface CompositionsFile {
    schema_version?: number;
    template: string;
    brand_dna?: {
        colors: Record<string, string>;
        fonts: { major: string; minor: string };
        slide_size_px: { w: number; h: number };
    };
    /** Design rules from Style Guide (v4) */
    design_rules?: {
        color_usage: string[];
        typography: string[];
        layout: string[];
        dos: string[];
        donts: string[];
    };
    /** Icon catalog from Icon Gallery (v4) */
    icon_catalog?: Array<{
        name: string;
        category: string;
        description: string;
        usage_hint?: string;
    }>;
    alias_map?: Record<string, { slide: number; shape_id: string; original_name: string }>;
    compositions: Record<string, CompositionEntry>;
}

export class GetCompositionDetailsTool extends BaseTool<'get_composition_details'> {
    readonly name = 'get_composition_details' as const;
    readonly isWriteOperation = false;

    constructor(plugin: ObsidianAgentPlugin) {
        super(plugin);
    }

    getDefinition(): ToolDefinition {
        return {
            name: 'get_composition_details',
            description:
                'Get detailed shape mappings and constraints for specific compositions from a template. ' +
                'Use this AFTER reading the template skill (which lists available compositions) ' +
                'to get the exact shape names, text capacity limits, and usage rules needed for create_pptx. ' +
                'Only request the compositions you actually need (typically 1-5 per presentation).',
            input_schema: {
                type: 'object',
                properties: {
                    template: {
                        type: 'string',
                        description:
                            'Template name (e.g., "acme-corporate"). ' +
                            'Must match the template field in the compositions.json file.',
                    },
                    compositions: {
                        type: 'array',
                        description:
                            'List of composition IDs to retrieve (e.g., ["chevron-kette", "kpi-dashboard"]). ' +
                            'IDs are listed in the template skill under "Compositions".',
                        items: { type: 'string' },
                    },
                },
                required: ['template', 'compositions'],
            },
        };
    }

    async execute(input: Record<string, unknown>, context: ToolExecutionContext): Promise<void> {
        const { callbacks } = context;
        const rawTemplate = (input.template as string ?? '').trim();
        const compositionIds = input.compositions as string[] ?? [];

        if (!rawTemplate) {
            callbacks.pushToolResult(this.formatError(new Error('Missing required parameter: template')));
            return;
        }

        if (compositionIds.length === 0) {
            callbacks.pushToolResult(this.formatError(new Error('Missing required parameter: compositions (array of IDs)')));
            return;
        }

        // Normalize template name (same logic as AnalyzePptxTemplateTool slug derivation)
        const template = rawTemplate.toLowerCase().replace(/[_\s]+/g, '-');

        // Find compositions.json via adapter (filesystem-level, cache-independent).
        // vault.getFileByPath() uses the metadata cache which may not know about
        // files written via vault.adapter.write() by AnalyzePptxTemplateTool.
        const filePath = `.obsilo/templates/${template}.compositions.json`;
        const adapter = this.app.vault.adapter;
        const fileExists = await adapter.exists(filePath);

        if (!fileExists) {
            // List available composition files for a helpful error message
            const templatesDir = '.obsilo/templates';
            const dirExists = await adapter.exists(templatesDir);
            let availableTemplates: string[] = [];

            if (dirExists) {
                try {
                    const listed = await adapter.list(templatesDir);
                    availableTemplates = (listed.files ?? [])
                        .filter((f: string) => f.endsWith('.compositions.json'))
                        .map((f: string) => f.replace('.obsilo/templates/', '').replace('.compositions.json', ''));
                } catch {
                    // Directory listing failed -- non-fatal
                }
            }

            if (availableTemplates.length > 0) {
                callbacks.pushToolResult(this.formatError(new Error(
                    `Compositions file not found: ${filePath}. ` +
                    `Available templates: ${availableTemplates.join(', ')}. ` +
                    `Use one of these as the template parameter.`,
                )));
            } else {
                callbacks.pushToolResult(this.formatError(new Error(
                    `Compositions file not found: ${filePath}. ` +
                    `No template compositions found in vault. ` +
                    `Run analyze_pptx_template first to generate them.`,
                )));
            }
            return;
        }

        try {
            const content = await adapter.read(filePath);
            const data = JSON.parse(content) as CompositionsFile;

            if (!data.compositions) {
                callbacks.pushToolResult(this.formatError(new Error(
                    'Invalid compositions.json: missing "compositions" field.',
                )));
                return;
            }

            // Filter to requested compositions
            const results: string[] = [];
            const notFound: string[] = [];

            for (const id of compositionIds) {
                const comp = data.compositions[id];
                if (!comp) {
                    notFound.push(id);
                    continue;
                }

                results.push(this.formatComposition(id, comp, data.schema_version ?? 1));
            }

            // Build response
            let output = `## Composition Details (${template})\n\n`;

            // Show BrandDNA for HTML mode reference
            if (data.brand_dna) {
                output += `### Brand-DNA\n`;
                output += `Fonts: ${data.brand_dna.fonts.major} (headings) / ${data.brand_dna.fonts.minor} (body)\n`;
                output += `Canvas: ${data.brand_dna.slide_size_px.w}x${data.brand_dna.slide_size_px.h}px\n`;
                output += `Colors: ${Object.entries(data.brand_dna.colors).map(([k, v]) => `${k}=#${v}`).join(', ')}\n\n`;
            }

            if (results.length > 0) {
                output += results.join('\n\n---\n\n');
            }

            if (notFound.length > 0) {
                output += `\n\nCompositions not found: ${notFound.join(', ')}. ` +
                    `Available: ${Object.keys(data.compositions).join(', ')}`;
            }

            callbacks.pushToolResult(output);
        } catch (error) {
            callbacks.pushToolResult(this.formatError(error));
        }
    }

    private formatComposition(id: string, comp: CompositionEntry, schemaVersion: number): string {
        const lines: string[] = [];
        const isV2 = schemaVersion >= 2;
        const isV4 = schemaVersion >= 4;

        lines.push(`### ${comp.name} (ID: ${id})`);
        lines.push(`**Slides:** ${comp.slides.join(', ')}`);
        if (isV4 && comp.recommended_pipeline) lines.push(`**Pipeline:** ${comp.recommended_pipeline}`);

        if (comp.narrative_phase && comp.narrative_phase !== 'any') lines.push(`**Narrative Phase:** ${comp.narrative_phase}`);
        if (comp.bedeutung) lines.push(`**Bedeutung:** ${comp.bedeutung}`);
        if (comp.einsetzen_wenn) lines.push(`**Einsetzen wenn:** ${comp.einsetzen_wenn}`);
        if (comp.nicht_einsetzen_wenn) lines.push(`**Nicht einsetzen wenn:** ${comp.nicht_einsetzen_wenn}`);
        if (comp.visual_structure) lines.push(`**Visual Structure:** ${comp.visual_structure}`);
        if (comp.has_fixed_visuals) lines.push(`**Fixed Visuals:** ${comp.decorative_element_count ?? 0} fixed decorative elements (icons/images that cannot be replaced)`);

        // Scaffolding info (v4)
        if (isV4 && comp.content_area) {
            const ca = comp.content_area;
            lines.push(`\n**Content Area:** x=${ca.x}, y=${ca.y}, w=${ca.w}, h=${ca.h} (px, 1280x720 canvas)`);
        }
        if (isV4 && comp.style_guide) {
            const sg = comp.style_guide;
            const parts: string[] = [];
            if (sg.title) parts.push(`Title: ${sg.title.font_size_pt}pt ${sg.title.color} ${sg.title.font_weight}`);
            if (sg.body) parts.push(`Body: ${sg.body.font_size_pt}pt ${sg.body.color}`);
            if (sg.accent_color) parts.push(`Accent: ${sg.accent_color}`);
            if (parts.length > 0) lines.push(`**Style Guide:** ${parts.join(' | ')}`);
        }
        if (isV4 && comp.layout_hint) lines.push(`**Layout Hint:** ${comp.layout_hint}`);
        if (isV4 && comp.scaffold_elements) lines.push(`**Scaffold Elements:** ${comp.scaffold_elements.length} (auto-injected via composition_id)`);
        if (isV4 && comp.html_skeleton) {
            lines.push('\n**HTML Skeleton (starting point):**');
            lines.push('```html');
            lines.push(comp.html_skeleton);
            lines.push('```');
        }

        // HTML mode hint for v4 compositions with html pipeline
        if (isV4 && comp.recommended_pipeline === 'html') {
            lines.push('\n**Recommended: Use HTML mode with composition_id:**');
            lines.push('```yaml');
            lines.push(`html: "<div ...>your content within content_area bounds</div>"`);
            lines.push(`composition_id: "${id}"  # scaffold auto-injected`);
            lines.push('```');
            lines.push('> Scaffold (header, footer, logo, deko) injected automatically. Design HTML within content_area bounds using style_guide colors/fonts.');
        }

        // Shape mappings: compact for HTML compositions, full for clone compositions
        if (isV4 && comp.recommended_pipeline === 'html') {
            // Compact clone-mode reference for HTML compositions
            const firstSlide = Object.entries(comp.shapes)[0];
            if (firstSlide) {
                const [slideNum, shapes] = firstSlide;
                const shapeNames = Object.keys(shapes);
                lines.push(`\n**Clone mode reference** (prefer HTML mode above):`);
                lines.push(`Slide ${slideNum}: ${shapeNames.join(', ')}`);
            }
        } else {
            // Full shape mappings (clone mode or non-v4)
            const keyLabel = isV2 ? 'semantic aliases' : 'shape names';
            for (const [slideNum, shapes] of Object.entries(comp.shapes)) {
                lines.push(`\n**Slide ${slideNum} -- Use these exact ${keyLabel} as content keys in create_pptx:**`);
                lines.push('```yaml');
                lines.push(`template_slide: ${slideNum}`);
                lines.push('content:');
                for (const [shapeName, detail] of Object.entries(shapes)) {
                    const constraints: string[] = [];
                    if (detail.shape_type === 'image') constraints.push('[IMAGE]');
                    if (detail.zweck) constraints.push(detail.zweck);
                    if (detail.fill_color) constraints.push(`fill: ${detail.fill_color}`);
                    if (detail.max_chars) constraints.push(`max ${detail.max_chars} chars`);
                    if (detail.font_size_pt) constraints.push(`${detail.font_size_pt}pt`);
                    if (detail.width_cm) constraints.push(`${detail.width_cm}cm wide`);
                    const constraintStr = constraints.length > 0 ? `  # ${constraints.join(', ')}` : '';
                    const placeholder = detail.shape_type === 'image' ? 'IMAGE PLACEHOLDER -- ask user or choose text-only composition' : 'YOUR TEXT HERE';
                    lines.push(`  "${shapeName}": "${placeholder}"${constraintStr}`);
                    if (detail.notes) lines.push(`    # ${detail.notes}`);
                }
                lines.push('```');
                if (isV2) {
                    lines.push('> Keys above are semantic aliases mapped to unique shape IDs. Use them EXACTLY as content keys.');
                } else {
                    lines.push('> Shape names above are OOXML name attributes. Use them EXACTLY as content keys.');
                }

                // Show repeatable groups for this slide
                const slideGroups = comp.repeatable_groups?.[slideNum];
                if (slideGroups && slideGroups.length > 0) {
                    lines.push('');
                    lines.push(`**Adaptable:** This slide has ${slideGroups.length} repeatable group(s). Shape count can be adjusted:`);
                    for (const rg of slideGroups) {
                        const shapeCount = rg.shapeNames.length;
                        const minCount = 2;
                        const maxCount = shapeCount + 3;
                        lines.push(`- **${rg.groupId}** (${rg.axis}): ${shapeCount}x shapes [${rg.shapeNames.slice(0, 3).join(', ')}${shapeCount > 3 ? '...' : ''}]. Adaptable to ${minCount}-${maxCount} shapes.`);
                        if (rg.columns.some(c => c.associatedShapes.length > 0)) {
                            const assocCount = rg.columns[0].associatedShapes.length;
                            lines.push(`  - Each shape has ${assocCount} associated element(s) that move together (e.g. description boxes below).`);
                        }
                        lines.push(`  - To use FEWER: only provide content for the shapes you need (extras are removed automatically).`);
                        lines.push(`  - To use MORE: provide content for additional shapes with incrementing numbers.`);
                    }
                }
            }
        }

        return lines.join('\n');
    }
}
