/**
 * GetCompositionDetailsTool — Two-Tier Retrieval (FEATURE-1115)
 *
 * Reads composition details from a template's compositions.json file.
 * Returns only the requested compositions (not all), keeping context window usage minimal.
 *
 * The compositions.json is generated by AnalyzePptxTemplateTool during template analysis
 * and enriched by the agent during visual inspection.
 */

import { BaseTool } from '../BaseTool';
import type { ToolDefinition, ToolExecutionContext } from '../types';
import type ObsidianAgentPlugin from '../../../main';

/** Shape detail within a composition */
interface ShapeDetail {
    zweck: string;
    max_chars?: number;
    min_chars?: number;
    font_size_pt?: number;
    width_cm?: number;
    notes?: string;
}

/** Composition entry in compositions.json */
interface CompositionEntry {
    name: string;
    slides: number[];
    bedeutung?: string;
    einsetzen_wenn?: string;
    nicht_einsetzen_wenn?: string;
    shapes: Record<string, Record<string, ShapeDetail>>;
}

/** Root structure of compositions.json */
interface CompositionsFile {
    template: string;
    compositions: Record<string, CompositionEntry>;
}

export class GetCompositionDetailsTool extends BaseTool<'get_composition_details'> {
    readonly name = 'get_composition_details' as const;
    readonly isWriteOperation = false;

    constructor(plugin: ObsidianAgentPlugin) {
        super(plugin);
    }

    getDefinition(): ToolDefinition {
        return {
            name: 'get_composition_details',
            description:
                'Get detailed shape mappings and constraints for specific compositions from a template. ' +
                'Use this AFTER reading the template skill (which lists available compositions) ' +
                'to get the exact shape names, text capacity limits, and usage rules needed for create_pptx. ' +
                'Only request the compositions you actually need (typically 1-5 per presentation).',
            input_schema: {
                type: 'object',
                properties: {
                    template: {
                        type: 'string',
                        description:
                            'Template name (e.g., "acme-corporate"). ' +
                            'Must match the template field in the compositions.json file.',
                    },
                    compositions: {
                        type: 'array',
                        description:
                            'List of composition IDs to retrieve (e.g., ["chevron-kette", "kpi-dashboard"]). ' +
                            'IDs are listed in the template skill under "Compositions".',
                        items: { type: 'string' },
                    },
                },
                required: ['template', 'compositions'],
            },
        };
    }

    async execute(input: Record<string, unknown>, context: ToolExecutionContext): Promise<void> {
        const { callbacks } = context;
        const rawTemplate = (input.template as string ?? '').trim();
        const compositionIds = input.compositions as string[] ?? [];

        if (!rawTemplate) {
            callbacks.pushToolResult(this.formatError(new Error('Missing required parameter: template')));
            return;
        }

        if (compositionIds.length === 0) {
            callbacks.pushToolResult(this.formatError(new Error('Missing required parameter: compositions (array of IDs)')));
            return;
        }

        // Normalize template name (same logic as AnalyzePptxTemplateTool slug derivation)
        const template = rawTemplate.toLowerCase().replace(/[_\s]+/g, '-');

        // Find compositions.json in vault
        const filePath = `.obsilo/templates/${template}.compositions.json`;
        const file = this.app.vault.getFileByPath(filePath);

        if (!file) {
            // List available composition files for a helpful error message
            const availableTemplates = this.app.vault.getFiles()
                .filter(f => f.path.startsWith('.obsilo/templates/') && f.path.endsWith('.compositions.json'))
                .map(f => f.path.replace('.obsilo/templates/', '').replace('.compositions.json', ''));

            if (availableTemplates.length > 0) {
                callbacks.pushToolResult(this.formatError(new Error(
                    `Compositions file not found: ${filePath}. ` +
                    `Available templates: ${availableTemplates.join(', ')}. ` +
                    `Use one of these as the template parameter.`,
                )));
            } else {
                callbacks.pushToolResult(this.formatError(new Error(
                    `Compositions file not found: ${filePath}. ` +
                    `No template compositions found in vault. ` +
                    `Run analyze_pptx_template first to generate them.`,
                )));
            }
            return;
        }

        try {
            const content = await this.app.vault.read(file);
            const data = JSON.parse(content) as CompositionsFile;

            if (!data.compositions) {
                callbacks.pushToolResult(this.formatError(new Error(
                    'Invalid compositions.json: missing "compositions" field.',
                )));
                return;
            }

            // Filter to requested compositions
            const results: string[] = [];
            const notFound: string[] = [];

            for (const id of compositionIds) {
                const comp = data.compositions[id];
                if (!comp) {
                    notFound.push(id);
                    continue;
                }

                results.push(this.formatComposition(id, comp));
            }

            // Build response
            let output = `## Composition Details (${template})\n\n`;

            if (results.length > 0) {
                output += results.join('\n\n---\n\n');
            }

            if (notFound.length > 0) {
                output += `\n\nCompositions not found: ${notFound.join(', ')}. ` +
                    `Available: ${Object.keys(data.compositions).join(', ')}`;
            }

            callbacks.pushToolResult(output);
        } catch (error) {
            callbacks.pushToolResult(this.formatError(error));
        }
    }

    private formatComposition(id: string, comp: CompositionEntry): string {
        const lines: string[] = [];

        lines.push(`### ${comp.name} (ID: ${id})`);
        lines.push(`**Slides:** ${comp.slides.join(', ')}`);

        if (comp.bedeutung) lines.push(`**Bedeutung:** ${comp.bedeutung}`);
        if (comp.einsetzen_wenn) lines.push(`**Einsetzen wenn:** ${comp.einsetzen_wenn}`);
        if (comp.nicht_einsetzen_wenn) lines.push(`**Nicht einsetzen wenn:** ${comp.nicht_einsetzen_wenn}`);

        // Shape mappings per slide
        for (const [slideNum, shapes] of Object.entries(comp.shapes)) {
            lines.push(`\n**Slide ${slideNum} — IMPORTANT: Use these exact shape names as content keys in create_pptx:**`);
            lines.push('```yaml');
            lines.push('# Copy this structure into your create_pptx call:');
            lines.push(`template_slide: ${slideNum}`);
            lines.push('content:');
            for (const [shapeName, detail] of Object.entries(shapes)) {
                const constraints: string[] = [];
                if (detail.max_chars) constraints.push(`max ${detail.max_chars} chars`);
                if (detail.font_size_pt) constraints.push(`${detail.font_size_pt}pt`);
                if (detail.width_cm) constraints.push(`${detail.width_cm}cm wide`);
                const constraintStr = constraints.length > 0 ? `  # ${constraints.join(', ')}` : '';
                lines.push(`  "${shapeName}": "YOUR TEXT HERE"${constraintStr}`);
                if (detail.notes) lines.push(`    # ${detail.notes}`);
            }
            lines.push('```');
            lines.push('> Shape names above are OOXML name attributes. Use them EXACTLY as content keys.');
            lines.push('> Do NOT use placeholder text (e.g. "Klicken Sie hier...") as content keys.');
        }

        return lines.join('\n');
    }
}
